version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: pg-primary
    env_file:
      - .env.primary
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /ora/data/postgres/data:/var/lib/postgresql/data
      - /ora/data/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - /ora/data/postgres/config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    restart: unless-stopped
